#!/bin/sh

if [ "$1" = configure ] ; then
    if [ ! -e /etc/apt/trusted.gpg.d/kylin-software-keyring.gpg ]; then
        ln -s /usr/share/keyrings/kylin-software-keyring.gpg \
              /etc/apt/trusted.gpg.d/kylin-software-keyring.gpg
    fi
fi
